import json
from pathlib import Path
import numpy as np

from scipy.signal import correlate


def extract_track_info(path: Path):

    with open(path) as f:
        data = json.load(f)

        local_res = [
            t for t in data if t["track_name"] == "Validation - Local Resolution"
        ]

        blocres = [
            (t["begin"], t["end"], float(t["description"].split(":")[-1]))
            for res in local_res
            for t in res["data"]
            if t["type"].startswith("DeepRes")
        ]

        buffer_size = blocres[-1][1]
        val_buffer = np.zeros([buffer_size])

        for start, end, val in blocres:
            val_buffer[start - 1 : end] = val

        return val_buffer


seqData = [
    {"resSeqName": "LEU", "resSeqNumber": 7, "scoreValue": 10.045},
    {"resSeqName": "ASN", "resSeqNumber": 8, "scoreValue": 9.605},
    {"resSeqName": "LEU", "resSeqNumber": 9, "scoreValue": 9.925},
    {"resSeqName": "ASP", "resSeqNumber": 10, "scoreValue": 8.174999999999999},
    {"resSeqName": "SER", "resSeqNumber": 11, "scoreValue": 8.945},
    {"resSeqName": "ILE", "resSeqNumber": 12, "scoreValue": 8.825},
    {"resSeqName": "ILE", "resSeqNumber": 13, "scoreValue": 6.83},
    {"resSeqName": "GLY", "resSeqNumber": 14, "scoreValue": 8.125},
    {"resSeqName": "ARG", "resSeqNumber": 15, "scoreValue": 8.07},
    {"resSeqName": "LEU", "resSeqNumber": 16, "scoreValue": 7.71},
    {"resSeqName": "LEU", "resSeqNumber": 17, "scoreValue": 0.07},
    {"resSeqName": "GLU", "resSeqNumber": 18, "scoreValue": 0.0},
    {"resSeqName": "VAL", "resSeqNumber": 19, "scoreValue": 0.05},
    {"resSeqName": "GLN", "resSeqNumber": 20, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 21, "scoreValue": 0.0},
    {"resSeqName": "SER", "resSeqNumber": 22, "scoreValue": 0.0},
    {"resSeqName": "ARG", "resSeqNumber": 23, "scoreValue": -0.0},
    {"resSeqName": "PRO", "resSeqNumber": 24, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 25, "scoreValue": 0.0},
    {"resSeqName": "LYS", "resSeqNumber": 26, "scoreValue": 0.0},
    {"resSeqName": "ASN", "resSeqNumber": 27, "scoreValue": 0.0},
    {"resSeqName": "VAL", "resSeqNumber": 28, "scoreValue": 0.11},
    {"resSeqName": "GLN", "resSeqNumber": 29, "scoreValue": 0.18},
    {"resSeqName": "LEU", "resSeqNumber": 30, "scoreValue": 7.914999999999999},
    {"resSeqName": "THR", "resSeqNumber": 31, "scoreValue": 7.94},
    {"resSeqName": "GLU", "resSeqNumber": 32, "scoreValue": 7.48},
    {"resSeqName": "ASN", "resSeqNumber": 33, "scoreValue": 7.83},
    {"resSeqName": "GLU", "resSeqNumber": 34, "scoreValue": 8.61},
    {"resSeqName": "ILE", "resSeqNumber": 35, "scoreValue": 8.29},
    {"resSeqName": "ARG", "resSeqNumber": 36, "scoreValue": 8.15},
    {"resSeqName": "GLY", "resSeqNumber": 37, "scoreValue": 8.335},
    {"resSeqName": "LEU", "resSeqNumber": 38, "scoreValue": 8.405},
    {"resSeqName": "CYS", "resSeqNumber": 39, "scoreValue": 8.52},
    {"resSeqName": "LEU", "resSeqNumber": 40, "scoreValue": 8.18},
    {"resSeqName": "LYS", "resSeqNumber": 41, "scoreValue": 8.62},
    {"resSeqName": "SER", "resSeqNumber": 42, "scoreValue": 1.585},
    {"resSeqName": "ARG", "resSeqNumber": 43, "scoreValue": 6.04},
    {"resSeqName": "GLU", "resSeqNumber": 44, "scoreValue": 1.52},
    {"resSeqName": "ILE", "resSeqNumber": 45, "scoreValue": 0.07},
    {"resSeqName": "PHE", "resSeqNumber": 46, "scoreValue": -0.0},
    {"resSeqName": "LEU", "resSeqNumber": 47, "scoreValue": 0.0},
    {"resSeqName": "SER", "resSeqNumber": 48, "scoreValue": -0.0},
    {"resSeqName": "GLN", "resSeqNumber": 49, "scoreValue": -0.0},
    {"resSeqName": "PRO", "resSeqNumber": 50, "scoreValue": 0.0},
    {"resSeqName": "ILE", "resSeqNumber": 51, "scoreValue": -0.0},
    {"resSeqName": "LEU", "resSeqNumber": 52, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 53, "scoreValue": 0.0},
    {"resSeqName": "GLU", "resSeqNumber": 54, "scoreValue": -0.0},
    {"resSeqName": "LEU", "resSeqNumber": 55, "scoreValue": 0.0},
    {"resSeqName": "GLU", "resSeqNumber": 56, "scoreValue": -0.0},
    {"resSeqName": "ALA", "resSeqNumber": 57, "scoreValue": 0.0},
    {"resSeqName": "PRO", "resSeqNumber": 58, "scoreValue": -0.0},
    {"resSeqName": "LEU", "resSeqNumber": 59, "scoreValue": 0.0},
    {"resSeqName": "LYS", "resSeqNumber": 60, "scoreValue": -0.0},
    {"resSeqName": "ILE", "resSeqNumber": 61, "scoreValue": 0.0},
    {"resSeqName": "CYS", "resSeqNumber": 62, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 63, "scoreValue": -0.0},
    {"resSeqName": "ALA", "resSeqNumber": 64, "scoreValue": -0.0},
    {"resSeqName": "ILE", "resSeqNumber": 65, "scoreValue": 0.0},
    {"resSeqName": "HIS", "resSeqNumber": 66, "scoreValue": -0.0},
    {"resSeqName": "GLY", "resSeqNumber": 67, "scoreValue": 0.0},
    {"resSeqName": "GLN", "resSeqNumber": 68, "scoreValue": 0.0},
    {"resSeqName": "TYR", "resSeqNumber": 69, "scoreValue": -0.0},
    {"resSeqName": "TYR", "resSeqNumber": 70, "scoreValue": 0.0},
    {"resSeqName": "ASP", "resSeqNumber": 71, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 72, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 73, "scoreValue": -0.0},
    {"resSeqName": "ARG", "resSeqNumber": 74, "scoreValue": -0.0},
    {"resSeqName": "LEU", "resSeqNumber": 75, "scoreValue": 0.0},
    {"resSeqName": "PHE", "resSeqNumber": 76, "scoreValue": -0.0},
    {"resSeqName": "GLU", "resSeqNumber": 77, "scoreValue": -0.0},
    {"resSeqName": "TYR", "resSeqNumber": 78, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 79, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 80, "scoreValue": 0.0},
    {"resSeqName": "PHE", "resSeqNumber": 81, "scoreValue": -0.0},
    {"resSeqName": "PRO", "resSeqNumber": 82, "scoreValue": 0.0},
    {"resSeqName": "PRO", "resSeqNumber": 83, "scoreValue": 0.0},
    {"resSeqName": "GLU", "resSeqNumber": 84, "scoreValue": 0.0},
    {"resSeqName": "SER", "resSeqNumber": 85, "scoreValue": -0.0},
    {"resSeqName": "ASN", "resSeqNumber": 86, "scoreValue": -0.0},
    {"resSeqName": "TYR", "resSeqNumber": 87, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 88, "scoreValue": 0.0},
    {"resSeqName": "PHE", "resSeqNumber": 89, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 90, "scoreValue": -0.0},
    {"resSeqName": "GLY", "resSeqNumber": 91, "scoreValue": 0.0},
    {"resSeqName": "ASP", "resSeqNumber": 92, "scoreValue": 0.0},
    {"resSeqName": "TYR", "resSeqNumber": 93, "scoreValue": 0.0},
    {"resSeqName": "VAL", "resSeqNumber": 94, "scoreValue": -0.01},
    {"resSeqName": "ASP", "resSeqNumber": 95, "scoreValue": 0.0},
    {"resSeqName": "ARG", "resSeqNumber": 96, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 97, "scoreValue": 0.0},
    {"resSeqName": "LYS", "resSeqNumber": 98, "scoreValue": 0.0},
    {"resSeqName": "GLN", "resSeqNumber": 99, "scoreValue": 0.0},
    {"resSeqName": "SER", "resSeqNumber": 100, "scoreValue": -0.02},
    {"resSeqName": "LEU", "resSeqNumber": 101, "scoreValue": -0.06},
    {"resSeqName": "GLU", "resSeqNumber": 102, "scoreValue": 0.01},
    {"resSeqName": "THR", "resSeqNumber": 103, "scoreValue": 0.0},
    {"resSeqName": "ILE", "resSeqNumber": 104, "scoreValue": 0.8500000000000001},
    {"resSeqName": "CYS", "resSeqNumber": 105, "scoreValue": 3.515},
    {"resSeqName": "LEU", "resSeqNumber": 106, "scoreValue": 0.015},
    {"resSeqName": "LEU", "resSeqNumber": 107, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 108, "scoreValue": 0.07},
    {"resSeqName": "ALA", "resSeqNumber": 109, "scoreValue": 0.83},
    {"resSeqName": "TYR", "resSeqNumber": 110, "scoreValue": 0.0},
    {"resSeqName": "LYS", "resSeqNumber": 111, "scoreValue": -0.0},
    {"resSeqName": "ILE", "resSeqNumber": 112, "scoreValue": 3.79},
    {"resSeqName": "LYS", "resSeqNumber": 113, "scoreValue": -0.0},
    {"resSeqName": "TYR", "resSeqNumber": 114, "scoreValue": -0.0},
    {"resSeqName": "PRO", "resSeqNumber": 115, "scoreValue": 0.0},
    {"resSeqName": "GLU", "resSeqNumber": 116, "scoreValue": 0.0},
    {"resSeqName": "ASN", "resSeqNumber": 117, "scoreValue": 0.0},
    {"resSeqName": "PHE", "resSeqNumber": 118, "scoreValue": -0.0},
    {"resSeqName": "PHE", "resSeqNumber": 119, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 120, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 121, "scoreValue": 0.0},
    {"resSeqName": "ARG", "resSeqNumber": 122, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 123, "scoreValue": 0.0},
    {"resSeqName": "ASN", "resSeqNumber": 124, "scoreValue": 0.0},
    {"resSeqName": "HIS", "resSeqNumber": 125, "scoreValue": 0.0},
    {"resSeqName": "GLU", "resSeqNumber": 126, "scoreValue": 0.0},
    {"resSeqName": "CYS", "resSeqNumber": 127, "scoreValue": -0.005},
    {"resSeqName": "ALA", "resSeqNumber": 128, "scoreValue": -0.03},
    {"resSeqName": "SER", "resSeqNumber": 129, "scoreValue": -0.0},
    {"resSeqName": "ILE", "resSeqNumber": 130, "scoreValue": 0.0},
    {"resSeqName": "ASN", "resSeqNumber": 131, "scoreValue": 0.005},
    {"resSeqName": "ARG", "resSeqNumber": 132, "scoreValue": 0.17},
    {"resSeqName": "ILE", "resSeqNumber": 133, "scoreValue": 0.0},
    {"resSeqName": "TYR", "resSeqNumber": 134, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 135, "scoreValue": 0.0},
    {"resSeqName": "PHE", "resSeqNumber": 136, "scoreValue": -0.02},
    {"resSeqName": "TYR", "resSeqNumber": 137, "scoreValue": 0.9450000000000001},
    {"resSeqName": "ASP", "resSeqNumber": 138, "scoreValue": -0.005},
    {"resSeqName": "GLU", "resSeqNumber": 139, "scoreValue": -0.01},
    {"resSeqName": "CYS", "resSeqNumber": 140, "scoreValue": 8.075},
    {"resSeqName": "LYS", "resSeqNumber": 141, "scoreValue": 1.67},
    {"resSeqName": "ARG", "resSeqNumber": 142, "scoreValue": 0.12},
    {"resSeqName": "ARG", "resSeqNumber": 143, "scoreValue": 0.09},
    {"resSeqName": "TYR", "resSeqNumber": 144, "scoreValue": 8.350000000000001},
    {"resSeqName": "ASN", "resSeqNumber": 145, "scoreValue": 8.035},
    {"resSeqName": "ILE", "resSeqNumber": 146, "scoreValue": 8.165},
    {"resSeqName": "LYS", "resSeqNumber": 147, "scoreValue": 8.02},
    {"resSeqName": "LEU", "resSeqNumber": 148, "scoreValue": 7.949999999999999},
    {"resSeqName": "TRP", "resSeqNumber": 149, "scoreValue": 8.379999999999999},
    {"resSeqName": "LYS", "resSeqNumber": 150, "scoreValue": 8.42},
    {"resSeqName": "THR", "resSeqNumber": 151, "scoreValue": 8.4},
    {"resSeqName": "PHE", "resSeqNumber": 152, "scoreValue": 8.48},
    {"resSeqName": "THR", "resSeqNumber": 153, "scoreValue": 8.45},
    {"resSeqName": "ASP", "resSeqNumber": 154, "scoreValue": 8.844999999999999},
    {"resSeqName": "CYS", "resSeqNumber": 155, "scoreValue": 7.575},
    {"resSeqName": "PHE", "resSeqNumber": 156, "scoreValue": -0.16},
    {"resSeqName": "ASN", "resSeqNumber": 157, "scoreValue": 0.065},
    {"resSeqName": "CYS", "resSeqNumber": 158, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 159, "scoreValue": 0.0},
    {"resSeqName": "PRO", "resSeqNumber": 160, "scoreValue": -0.0},
    {"resSeqName": "ILE", "resSeqNumber": 161, "scoreValue": -0.0},
    {"resSeqName": "ALA", "resSeqNumber": 162, "scoreValue": -0.0},
    {"resSeqName": "ALA", "resSeqNumber": 163, "scoreValue": 0.0},
    {"resSeqName": "ILE", "resSeqNumber": 164, "scoreValue": 0.0},
    {"resSeqName": "VAL", "resSeqNumber": 165, "scoreValue": 0.0},
    {"resSeqName": "ASP", "resSeqNumber": 166, "scoreValue": 0.0},
    {"resSeqName": "GLU", "resSeqNumber": 167, "scoreValue": -0.0},
    {"resSeqName": "LYS", "resSeqNumber": 168, "scoreValue": -0.0},
    {"resSeqName": "ILE", "resSeqNumber": 169, "scoreValue": 0.0},
    {"resSeqName": "PHE", "resSeqNumber": 170, "scoreValue": 0.0},
    {"resSeqName": "CYS", "resSeqNumber": 171, "scoreValue": 0.0},
    {"resSeqName": "CYS", "resSeqNumber": 172, "scoreValue": 0.0},
    {"resSeqName": "HIS", "resSeqNumber": 173, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 174, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 175, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 176, "scoreValue": 0.0},
    {"resSeqName": "SER", "resSeqNumber": 177, "scoreValue": -0.0},
    {"resSeqName": "PRO", "resSeqNumber": 178, "scoreValue": 0.0},
    {"resSeqName": "ASP", "resSeqNumber": 179, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 180, "scoreValue": 0.0},
    {"resSeqName": "GLN", "resSeqNumber": 181, "scoreValue": -0.0},
    {"resSeqName": "SER", "resSeqNumber": 182, "scoreValue": 0.0},
    {"resSeqName": "MET", "resSeqNumber": 183, "scoreValue": 0.0},
    {"resSeqName": "GLU", "resSeqNumber": 184, "scoreValue": 0.0},
    {"resSeqName": "GLN", "resSeqNumber": 185, "scoreValue": 0.0},
    {"resSeqName": "ILE", "resSeqNumber": 186, "scoreValue": 0.0},
    {"resSeqName": "ARG", "resSeqNumber": 187, "scoreValue": -0.0},
    {"resSeqName": "ARG", "resSeqNumber": 188, "scoreValue": 0.0},
    {"resSeqName": "ILE", "resSeqNumber": 189, "scoreValue": 0.0},
    {"resSeqName": "MET", "resSeqNumber": 190, "scoreValue": 0.0},
    {"resSeqName": "ARG", "resSeqNumber": 191, "scoreValue": -0.0},
    {"resSeqName": "PRO", "resSeqNumber": 192, "scoreValue": 0.41},
    {"resSeqName": "THR", "resSeqNumber": 193, "scoreValue": -0.0},
    {"resSeqName": "ASP", "resSeqNumber": 194, "scoreValue": 0.005},
    {"resSeqName": "VAL", "resSeqNumber": 195, "scoreValue": -0.0},
    {"resSeqName": "PRO", "resSeqNumber": 196, "scoreValue": 0.0},
    {"resSeqName": "ASP", "resSeqNumber": 197, "scoreValue": 0.0},
    {"resSeqName": "GLN", "resSeqNumber": 198, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 199, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 200, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 201, "scoreValue": 0.0},
    {"resSeqName": "CYS", "resSeqNumber": 202, "scoreValue": -0.0},
    {"resSeqName": "ASP", "resSeqNumber": 203, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 204, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 205, "scoreValue": 0.0},
    {"resSeqName": "TRP", "resSeqNumber": 206, "scoreValue": -0.0},
    {"resSeqName": "SER", "resSeqNumber": 207, "scoreValue": -0.0},
    {"resSeqName": "ASP", "resSeqNumber": 208, "scoreValue": -0.0},
    {"resSeqName": "PRO", "resSeqNumber": 209, "scoreValue": 0.0},
    {"resSeqName": "ASP", "resSeqNumber": 210, "scoreValue": 0.0},
    {"resSeqName": "LYS", "resSeqNumber": 211, "scoreValue": 0.0},
    {"resSeqName": "ASP", "resSeqNumber": 212, "scoreValue": 0.0},
    {"resSeqName": "VAL", "resSeqNumber": 213, "scoreValue": 0.0},
    {"resSeqName": "GLN", "resSeqNumber": 214, "scoreValue": -0.0},
    {"resSeqName": "GLY", "resSeqNumber": 215, "scoreValue": -0.0},
    {"resSeqName": "TRP", "resSeqNumber": 216, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 217, "scoreValue": 0.0},
    {"resSeqName": "GLU", "resSeqNumber": 218, "scoreValue": -0.0},
    {"resSeqName": "ASN", "resSeqNumber": 219, "scoreValue": -0.0},
    {"resSeqName": "ASP", "resSeqNumber": 220, "scoreValue": 0.0},
    {"resSeqName": "ARG", "resSeqNumber": 221, "scoreValue": -0.0},
    {"resSeqName": "GLY", "resSeqNumber": 222, "scoreValue": 0.0},
    {"resSeqName": "VAL", "resSeqNumber": 223, "scoreValue": -0.0},
    {"resSeqName": "SER", "resSeqNumber": 224, "scoreValue": 0.0},
    {"resSeqName": "PHE", "resSeqNumber": 225, "scoreValue": -0.0},
    {"resSeqName": "THR", "resSeqNumber": 226, "scoreValue": 0.0},
    {"resSeqName": "PHE", "resSeqNumber": 227, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 228, "scoreValue": 0.0},
    {"resSeqName": "ALA", "resSeqNumber": 229, "scoreValue": 0.0},
    {"resSeqName": "GLU", "resSeqNumber": 230, "scoreValue": 0.0},
    {"resSeqName": "VAL", "resSeqNumber": 231, "scoreValue": 0.0},
    {"resSeqName": "VAL", "resSeqNumber": 232, "scoreValue": -0.0},
    {"resSeqName": "ALA", "resSeqNumber": 233, "scoreValue": 0.0},
    {"resSeqName": "LYS", "resSeqNumber": 234, "scoreValue": -0.0},
    {"resSeqName": "PHE", "resSeqNumber": 235, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 236, "scoreValue": 0.0},
    {"resSeqName": "HIS", "resSeqNumber": 237, "scoreValue": -0.0},
    {"resSeqName": "LYS", "resSeqNumber": 238, "scoreValue": 0.0},
    {"resSeqName": "HIS", "resSeqNumber": 239, "scoreValue": 0.0},
    {"resSeqName": "ASP", "resSeqNumber": 240, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 241, "scoreValue": 0.0},
    {"resSeqName": "ASP", "resSeqNumber": 242, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 243, "scoreValue": 0.0},
    {"resSeqName": "ILE", "resSeqNumber": 244, "scoreValue": 0.0},
    {"resSeqName": "CYS", "resSeqNumber": 245, "scoreValue": 0.0},
    {"resSeqName": "ARG", "resSeqNumber": 246, "scoreValue": -0.0},
    {"resSeqName": "ALA", "resSeqNumber": 247, "scoreValue": -0.0},
    {"resSeqName": "HIS", "resSeqNumber": 248, "scoreValue": 0.0},
    {"resSeqName": "GLN", "resSeqNumber": 249, "scoreValue": 0.0},
    {"resSeqName": "VAL", "resSeqNumber": 250, "scoreValue": -0.0},
    {"resSeqName": "VAL", "resSeqNumber": 251, "scoreValue": -0.0},
    {"resSeqName": "GLU", "resSeqNumber": 252, "scoreValue": 0.0},
    {"resSeqName": "ASP", "resSeqNumber": 253, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 254, "scoreValue": 0.0},
    {"resSeqName": "TYR", "resSeqNumber": 255, "scoreValue": -0.0},
    {"resSeqName": "GLU", "resSeqNumber": 256, "scoreValue": -0.0},
    {"resSeqName": "PHE", "resSeqNumber": 257, "scoreValue": -0.0},
    {"resSeqName": "PHE", "resSeqNumber": 258, "scoreValue": 0.0},
    {"resSeqName": "ALA", "resSeqNumber": 259, "scoreValue": -0.0},
    {"resSeqName": "LYS", "resSeqNumber": 260, "scoreValue": 0.0},
    {"resSeqName": "ARG", "resSeqNumber": 261, "scoreValue": -0.0},
    {"resSeqName": "GLN", "resSeqNumber": 262, "scoreValue": -0.0},
    {"resSeqName": "LEU", "resSeqNumber": 263, "scoreValue": 0.0},
    {"resSeqName": "VAL", "resSeqNumber": 264, "scoreValue": 0.0},
    {"resSeqName": "THR", "resSeqNumber": 265, "scoreValue": -0.0},
    {"resSeqName": "LEU", "resSeqNumber": 266, "scoreValue": 0.0},
    {"resSeqName": "PHE", "resSeqNumber": 267, "scoreValue": -0.0},
    {"resSeqName": "SER", "resSeqNumber": 268, "scoreValue": 0.0},
    {"resSeqName": "ALA", "resSeqNumber": 269, "scoreValue": -0.0},
    {"resSeqName": "PRO", "resSeqNumber": 270, "scoreValue": -0.0},
    {"resSeqName": "ASN", "resSeqNumber": 271, "scoreValue": -0.0},
    {"resSeqName": "TYR", "resSeqNumber": 272, "scoreValue": 0.0},
    {"resSeqName": "CYS", "resSeqNumber": 273, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 274, "scoreValue": 0.0},
    {"resSeqName": "GLU", "resSeqNumber": 275, "scoreValue": 0.0},
    {"resSeqName": "PHE", "resSeqNumber": 276, "scoreValue": 0.0},
    {"resSeqName": "ASP", "resSeqNumber": 277, "scoreValue": 0.0},
    {"resSeqName": "ASN", "resSeqNumber": 278, "scoreValue": 0.0},
    {"resSeqName": "ALA", "resSeqNumber": 279, "scoreValue": 0.0},
    {"resSeqName": "GLY", "resSeqNumber": 280, "scoreValue": 0.0},
    {"resSeqName": "ALA", "resSeqNumber": 281, "scoreValue": -0.0},
    {"resSeqName": "MET", "resSeqNumber": 282, "scoreValue": 0.0},
    {"resSeqName": "MET", "resSeqNumber": 283, "scoreValue": 0.0},
    {"resSeqName": "SER", "resSeqNumber": 284, "scoreValue": 0.0},
    {"resSeqName": "VAL", "resSeqNumber": 285, "scoreValue": -0.0},
    {"resSeqName": "ASP", "resSeqNumber": 286, "scoreValue": 0.0},
    {"resSeqName": "GLU", "resSeqNumber": 287, "scoreValue": 0.0},
    {"resSeqName": "THR", "resSeqNumber": 288, "scoreValue": -0.0},
    {"resSeqName": "LEU", "resSeqNumber": 289, "scoreValue": -0.0},
    {"resSeqName": "MET", "resSeqNumber": 290, "scoreValue": 0.0},
    {"resSeqName": "CYS", "resSeqNumber": 291, "scoreValue": 0.0},
    {"resSeqName": "SER", "resSeqNumber": 292, "scoreValue": 0.0},
    {"resSeqName": "PHE", "resSeqNumber": 293, "scoreValue": -0.0},
    {"resSeqName": "GLN", "resSeqNumber": 294, "scoreValue": 0.0},
    {"resSeqName": "ILE", "resSeqNumber": 295, "scoreValue": 0.0},
    {"resSeqName": "LEU", "resSeqNumber": 296, "scoreValue": -0.0},
    {"resSeqName": "LYS", "resSeqNumber": 297, "scoreValue": -0.0},
    {"resSeqName": "PRO", "resSeqNumber": 298, "scoreValue": 0.0},
    {"resSeqName": "ALA", "resSeqNumber": 299, "scoreValue": 0.0},
]


def extract_seq_data():
    data = [(e["resSeqNumber"], e["scoreValue"]) for e in seqData]

    buffer_size = data[-1][0]
    val_buffer = np.zeros([buffer_size + 1])

    for idx, val in data:
        val_buffer[idx] = val

    return val_buffer


def normalized(a):
    return a / np.linalg.norm(a)


def main():
    reference = extract_track_info(
        Path("/home/max/Downloads/emd-12665-bws/emd-12665-chain-b.json")
    )
    converted = extract_seq_data()

    max_shape = max(reference.shape[0], converted.shape[0])
    a = np.pad(reference, [0, max_shape - reference.shape[0]])
    b = np.pad(converted, [0, max_shape - converted.shape[0]])

    a = normalized(a)
    b = normalized(b)

    print(np.max(np.correlate(a, b, "full")))
    

if __name__ == "__main__":
    main()
